### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by hamza-nb** [papasnippy/react-bolivianite-grid#1]
i can't see the grid when i implemented it in my project

**Comment by papasnippy** [comment]
I cannot know your implementation.

**Comment by hamza-nb** [comment]
See this link please ----> https://codesandbox.io/s/wonderful-morse-mfzeu?file=/src/App.js

**Comment by Hamza-Nait** [comment]
See this link please ---->
https://codesandbox.io/s/wonderful-morse-mfzeu?file=/src/App.js

Le jeu. 30 juil. 2020 à 18:37, Hamza Nait Boubker <hamzanb8@gmail.com> a
écrit :

>
>

**Comment by papasnippy** [comment]
Grid does not have fixed size, it depend on size of the container and will automatically fill all available space.
```tsx
import React from "react";
import Main from "./components/main";

export default function App() {
  return (
    <div style={{ height: '90vh', width: '90vw' }}>
      <Main />
    </div>
  );
}
```

**Comment by hamza-nb** [comment]
Hey, please help me, I have another problem with this example ---> https://codesandbox.io/s/wonderful-morse-mfzeu?file=/src/App.js

**Comment by hamza-nb** [comment]
> Grid does not have fixed size, it depend on size of the container and will automatically fill all available space.
> 
> ```tsx
> import React from "react";
> import Main from "./components/main";
> 
> export default function App() {
>   return (
>     <div style={{ height: '90vh', width: '90vw' }}>
>       <Main />
>     </div>
>   );
> }
> ```

Hey, please help me, I have another problem with this example ---> https://codesandbox.io/s/wonderful-morse-mfzeu?file=/src/App.js

**Comment by papasnippy** [comment]
CSS modules apparently do not work in codesandbox: `className={Style.exampleContainer}` is not translated into actual web page. Install and develop in local environment.
